name: tekartik_deezer_api
description: Simple deezer api wrapper
version: 0.1.1
publish_to: none

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  path: '>=1.8.0'
  tekartik_app_http:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app_http
    version: '>=0.1.0'
  cv: '>=0.2.14'
  http:
dev_dependencies:
  lints: '>=2.0.0'
  test: '>=1.21.0'
