name: tekartik_deezer_api
description: Simple deezer api wrapper
version: 0.1.3
publish_to: none

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  path: ">=1.9.0"
  tekartik_app_http:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_http
    version: '>=0.1.0'
  cv: ">=1.1.0+4"
  http:
  web: '>=0.5.1'
dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
resolution: workspace
