name: tekartik_mailjet
description: Mail jet http client.
version: 0.1.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  cv: '>=0.2.14'
  path:
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      path: http
      ref: dart3a
    version: '>=0.5.5'
dev_dependencies:
  lints: '>=2.0.0'
  test: '>=1.21.0'
