name: tekartik_mailjet
description: Mail jet http client.
version: 0.1.1
publish_to: none

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  cv: ">=1.1.0+4"
  path: ">=1.9.0"
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      path: http
      ref: dart3a
    version: '>=0.5.5'
dev_dependencies:
  lints: '>=5.0.0'
  test: ">=1.24.0"
resolution: workspace
