name: tekartik_stripe_api
description: A starting point for Dart libraries or applications.
version: 1.0.2
publish_to: none

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  path: ">=1.9.0"
  http:
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      path: http
    version: '>=0.7.5'
  process_run: ">=1.2.1+1"
  cv: ">=1.1.0+4"
dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
resolution: workspace
